[package]
name = "bevy-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.1"
rand = "0.8.5"
bevy-inspector-egui = "0.13.0"
serde = "1.0.147"
serde_json = "1.0"

[workspace]
resolver = "2"